name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Copy jar file to another directory
        run: sudo cp /home/ubuntu/actions-runner-nginx/_work/nginx-test/nginx-test/build/libs/reverse-0.0.1-SNAPSHOT.jar /home/ubuntu/artifact-nginx

      - name: Finally Run the artifact nginx service
        run: sudo systemctl restart artifact-nginx.service
